### ISSUE TITLE
(feat. request) read marks from different branch

### ISSUE THREAD

**Issue by ChHaeni** [MeanderingProgrammer/harpoon-core.nvim#1]
Hi,

Thanks for this great harpoon fork! I'm not sure how far you want to extend this plugin, but it would seem very handy to me, if one could read existing marks from a different branch (in the same project). This could facilitate switching to a new branch, but keeping the same marks in harpoon-core...

Cheers, Chris

**Comment by MeanderingProgrammer** [comment]
Hi Chris,

Thank you for the interest, I am glad you're liking this fork :)
Sorry for the late response, I've definitely neglected coming back to this repo for some time.

In general my goals with this plugin were more a learning experience for myself and to keep a version of Harpoon around that had the features that I use. Though I personally don't use the branch level marks I tend to only keep marks at a project level and add / remove them as I work on different things.

However I think this feature sounds neat and I agree it could be useful, but I'll need your input on how exactly something like this should work. 

What were you thinking in terms of how users would interact with this feature?

Would this be a separate UI you could enter that shows branches, then you go into branches to see the marks in them, where selecting one would then change the branch you are on as well as open the file?

Or would it just be a JSON blob you could dump somewhere with your branches and marks and what you do with that information from there is up to you.

Any and all ideas you have about this kind of a feature are appreciated!

**Comment by MeanderingProgrammer** [comment]
Feel free to re-open if you come back to this, closing for the time being.
